site_name: Curious Python Course
site_description: 'Practical Python training material'
site_author: 'Holger Joukl'
docs_dir: docs/
repo_name: 'hjoukl/cpycourse'
repo_url: 'https://github.com/hjoukl/cpycourse'

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - Home: index.md
    - Training:
        - Tutorial: training/tutorial.md
        - Main Course:
            - "A Curious Python: Main Course": training/main-course/main-course.md
            - "Chapter 1: Functions": training/main-course/functions.md
            - "Chapter N: Python Objects": training/main-course/objects.md
        - Oddities: training/oddjob.md
        - Cheatsheet: training/cheatsheet.md
    - Lessons:
        - Lesson 1: lessons/hello-world.md
    - Python:
        - Python: python/python.md
        - Why Python?: python/why-python.md
        - A brief history of Python: python/python-history.md
    - About:
        - Curious Python Course: about/curious-python-course.md
        - License: about/license.md
        - Legal: about/legal.md
        - Contributors: about/cpycourse-contributors.md

markdown_extensions:
    - toc:
        permalink: "#"
    - admonition
    - def_list
        
copyright: Copyright &copy; 2020 the <a href="/about/cpycourse-contributors.md">cpycourse contributors</a>.
