site_name: Test docs
site_description: 'A docs test'
site_author: 'Holger'
docs_dir: docs/
repo_name: 'hjoukl/test-gh-pages'
repo_url: 'https://github.com/hjoukl/test-gh-pages'

theme:
  name: 'mkdocs'

nav:
    - Home: index.md
    - About: about.md
