site_name: Curious Python Course
site_description: 'Practical Python training material'
site_author: 'Holger Joukl'
docs_dir: docs/
repo_name: 'hjoukl/test-gh-pages'
repo_url: 'https://github.com/hjoukl/test-gh-pages'

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - Home: index.md
    - Training:
        - Tutorial: training/tutorial.md
        - Main Course: training/main-course.md
        - Oddities: training/oddjob.md
        - Cheatsheet: training/cheatsheet.md
    - Lessons:
        - Lesson 1: lessons/hello-world.md
    - Python:
        - Python: python/python.md
        - Why Python?: python/why-python.md
        - A brief history of Python: python/python-history.md
    - About:
        - Curious Python Course: about/curious-python-course.md
        - License: about/license.md

markdown_extensions:
    - toc:
        permalink: "#"
